version: '3.8'
services:
  api_caps_alpha_1:
    build: .
    restart: always
    environment:
      -  PORT=3001
      -  DB_HOST=db_caps
      -  DB_PORT=5432
      -  DB_USER=postgres
      -  DB_PASSWORD=postgres
      -  DB_NAME=postgres
      -  DB_DATABASE=caps_alpha
      -  JWT_SECRET=1231nsadnaj2i3j2iji2jii2j32j
    ports:
      - '3001:3001'
    depends_on:
      - db_caps
    links:
      - db_caps 
    command: npm run watch
    volumes:
      - type: bind
        source: ./app 
        target: /usr/caps_alpha/app

  db_caps:
    build: ./docker/db/
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '8002:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local